import { notFound } from "next/navigation";
import { revalidatePath } from "next/cache";
import type { OrderStatus } from "@prisma/client";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireSuperAdmin } from "@/lib/super-admin";
import { jsonForAudit } from "@/lib/platform-config";
import { sendOrderStatusNotification } from "@/lib/whatsapp";
import { transitionOrder } from "@/lib/order-lifecycle";

const statuses = ["NEW","CONFIRMED","PREPARING","READY","ASSIGNED_TO_DRIVER","OUT_FOR_DELIVERY","DELIVERED","COMPLETED","CANCELLED","REJECTED","FAILED_DELIVERY"] as const;
async function updateOrder(data: FormData) { "use server"; const session = await requireSuperAdmin(); const parsed = z.object({ id: z.string().cuid(), customerName: z.string().trim().min(2).max(120), customerPhone: z.string().trim().min(8).max(30), deliveryAddress: z.string().trim().max(800).optional(), deliveryNotes: z.string().trim().max(1000).optional(), notes: z.string().trim().max(1000).optional() }).parse({ id: data.get("id"), customerName: data.get("customerName"), customerPhone: data.get("customerPhone"), deliveryAddress: String(data.get("deliveryAddress") || "") || undefined, deliveryNotes: String(data.get("deliveryNotes") || "") || undefined, notes: String(data.get("notes") || "") || undefined }); const previous = await prisma.order.findUniqueOrThrow({ where: { id: parsed.id }, select: { customerName: true, customerPhone: true, deliveryAddress: true, deliveryNotes: true, notes: true } }); const next = await prisma.order.update({ where: { id: parsed.id }, data: { customerName: parsed.customerName, customerPhone: parsed.customerPhone, deliveryAddress: parsed.deliveryAddress, deliveryNotes: parsed.deliveryNotes, notes: parsed.notes } }); await prisma.auditLog.create({ data: { action: "ORDER_DETAILS_UPDATED_BY_ADMIN", entity: "Order", entityId: parsed.id, restaurantId: next.restaurantId, userId: session.user.id, metadata: jsonForAudit({ previous, next: parsed }) } }); revalidatePath(`/super-admin/orders/${parsed.id}`); revalidatePath(`/order/${next.accessToken}`); }
async function updateStatus(data: FormData) { "use server"; const session = await requireSuperAdmin(); const parsed = z.object({ id: z.string().cuid(), status: z.enum(statuses) }).parse({ id: data.get("id"), status: data.get("status") }); const order = await prisma.order.findUniqueOrThrow({ where: { id: parsed.id }, select: { id: true, status: true, restaurantId: true, restaurant: { select: { name: true, nameAr: true, locale: true } } } }); const result = await transitionOrder({ orderId: order.id, restaurantId: order.restaurantId, actorUserId: session.user.id, actorRoles: session.user.roles, next: parsed.status, action: "STATUS_CHANGED_BY_SUPER_ADMIN" }); if (!result.changed) return; await prisma.auditLog.create({ data: { action: "ORDER_STATUS_CHANGED_BY_ADMIN", entity: "Order", entityId: order.id, restaurantId: order.restaurantId, userId: session.user.id, metadata: { previous: result.previous, next: result.current } } }); const baseUrl = (process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000").replace(/\/$/, ""); await sendOrderStatusNotification({ orderId: result.order.id, status: result.current as OrderStatus, orderNumber: result.order.orderNumber, customerPhone: result.order.customerPhone, restaurantName: order.restaurant.nameAr || order.restaurant.name, customerOrderUrl: `${baseUrl}/order/${result.order.accessToken}`, language: order.restaurant.locale }); revalidatePath(`/super-admin/orders/${order.id}`); revalidatePath(`/order/${result.order.accessToken}`); }
export default async function AdminOrderDetails({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const order = await prisma.order.findUnique({ where: { id }, include: { restaurant: { select: { id: true, name: true, nameAr: true } }, branch: { select: { name: true } }, items: { include: { extras: true, options: true } }, statusHistory: { orderBy: { createdAt: "desc" } }, actionLogs: { orderBy: { createdAt: "desc" }, take: 30 } } }); if (!order) notFound(); return <><header className="admin-header"><div><h1>الطلب {order.orderNumber}</h1><p>{order.restaurant.nameAr || order.restaurant.name} · {order.branch?.name ?? "الفرع الرئيسي"}</p></div><a className="admin-button" href={`/order/${order.accessToken}`} target="_blank">فتح صفحة الطلب</a></header><div className="admin-grid"><section className="admin-card"><h2>بيانات العميل والتوصيل</h2><form action={updateOrder} className="admin-form"><input type="hidden" name="id" value={order.id}/><label>اسم العميل<input name="customerName" defaultValue={order.customerName}/></label><label>الهاتف<input name="customerPhone" defaultValue={order.customerPhone}/></label><label className="full">العنوان<textarea name="deliveryAddress" defaultValue={order.deliveryAddress ?? ""}/></label><label className="full">تعليمات التوصيل<textarea name="deliveryNotes" defaultValue={order.deliveryNotes ?? ""}/></label><label className="full">ملاحظات الطلب<textarea name="notes" defaultValue={order.notes ?? ""}/></label><button>حفظ البيانات</button></form></section><section className="admin-card"><h2>الحالة والإجمالي</h2><form action={updateStatus} className="admin-form"><input type="hidden" name="id" value={order.id}/><label className="full">حالة الطلب<select name="status" defaultValue={order.status}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><button>تحديث الحالة</button></form><p>الفرعي: {Number(order.subtotal).toLocaleString("ar-EG")} ج.م</p><p>التوصيل: {Number(order.deliveryFee).toLocaleString("ar-EG")} ج.م</p><p>الخدمة: {Number(order.serviceFee).toLocaleString("ar-EG")} ج.م</p><p>الضريبة: {Number(order.taxAmount).toLocaleString("ar-EG")} ج.م</p><h3>الإجمالي: {Number(order.total).toLocaleString("ar-EG")} ج.م</h3></section></div><section className="admin-card admin-section"><h2>المنتجات</h2>{order.items.map((item) => <article key={item.id}><b>{item.quantity} × {item.productName}</b> — {Number(item.unitPrice).toLocaleString("ar-EG")} ج.م{item.options.length > 0 && <p>{item.options.map((option) => option.name).join("، ")}</p>}{item.extras.length > 0 && <p>{item.extras.map((extra) => extra.name).join("، ")}</p>}</article>)}</section><section className="admin-card admin-section"><h2>سجل الحالة</h2>{order.statusHistory.map((item) => <p key={item.id}>{item.status} — {new Intl.DateTimeFormat("ar-EG", { dateStyle: "short", timeStyle: "short" }).format(item.createdAt)}</p>)}</section></>; }
