import { revalidatePath, revalidateTag } from "next/cache";
import { getLocale, getTranslations } from "next-intl/server";
import { prisma } from "@/lib/prisma";
import { requireTenant } from "@/lib/tenant";

export const dynamic = "force-dynamic";
export default async function OptionsPage() {
  const { restaurantId } = await requireTenant();
  const [t, locale, groups, products] = await Promise.all([
    getTranslations("restaurantWorkflow.options"), getLocale(),
    prisma.productOptionGroup.findMany({where:{restaurantId},orderBy:{sortOrder:"asc"},include:{options:{include:{option:true},orderBy:{sortOrder:"asc"}},products:{select:{productId:true}}}}),
    prisma.product.findMany({where:{restaurantId},orderBy:{name:"asc"},select:{id:true,name:true,nameAr:true}}),
  ]);
  async function createGroup(form:FormData){"use server";const{restaurantId}=await requireTenant();const name=String(form.get("name")||"").trim();if(name.length<2)return;const min=Math.max(0,Number(form.get("min"))||0);const max=Math.max(min,Number(form.get("max"))||1);await prisma.productOptionGroup.create({data:{restaurantId,name,nameAr:String(form.get("nameAr")||"").trim()||null,isRequired:form.get("required")==="on",minSelections:form.get("required")==="on"?Math.max(1,min):min,maxSelections:max}});revalidatePath("/dashboard/options");}
  async function createOption(form:FormData){"use server";const{restaurantId}=await requireTenant();const groupId=String(form.get("groupId"));const group=await prisma.productOptionGroup.findFirst({where:{id:groupId,restaurantId},select:{id:true}});if(!group)return;const name=String(form.get("name")||"").trim();if(name.length<2)return;const option=await prisma.productOption.create({data:{restaurantId,name,nameAr:String(form.get("nameAr")||"").trim()||null,description:String(form.get("description")||"").trim()||null,priceAdjustment:Number(form.get("price"))||0,standaloneProductId:String(form.get("standaloneProductId")||"")||null}});await prisma.productOptionGroupItem.create({data:{groupId,optionId:option.id}});revalidatePath("/dashboard/options");revalidateTag("public-menu");}
  async function attach(form:FormData){"use server";const{restaurantId}=await requireTenant();const groupId=String(form.get("groupId"));const productId=String(form.get("productId"));const [group,product]=await Promise.all([prisma.productOptionGroup.findFirst({where:{id:groupId,restaurantId},select:{id:true}}),prisma.product.findFirst({where:{id:productId,restaurantId},select:{id:true}})]);if(!group||!product)return;await prisma.productOptionGroupProduct.upsert({where:{groupId_productId:{groupId,productId}},create:{groupId,productId},update:{}});revalidatePath("/dashboard/options");revalidateTag("public-menu");}
  return <section className="dash-main"><header><div><h1>{t("title")}</h1><p>{t("subtitle")}</p></div></header><div className="workflow-grid"><form action={createGroup} className="dash-card settings-grid"><h2>{t("newGroup")}</h2><label>{t("name")}<input name="name" required/></label><label>{t("nameAr")}<input name="nameAr" dir="rtl"/></label><label>{t("min")}<input name="min" type="number" min="0" defaultValue="0"/></label><label>{t("max")}<input name="max" type="number" min="1" defaultValue="1"/></label><label className="check-label"><input name="required" type="checkbox"/>{t("required")}</label><button className="button primary">{t("save")}</button></form><form action={createOption} className="dash-card settings-grid"><h2>{t("newOption")}</h2><label>{t("group")}<select name="groupId" required>{groups.map(g=><option key={g.id} value={g.id}>{locale==="ar"&&g.nameAr?g.nameAr:g.name}</option>)}</select></label><label>{t("name")}<input name="name" required/></label><label>{t("nameAr")}<input name="nameAr" dir="rtl"/></label><label>{t("description")}<input name="description"/></label><label>{t("price")}<input name="price" type="number" step=".01" defaultValue="0"/></label><label>{t("standalone")}<select name="standaloneProductId"><option value="">—</option>{products.map(p=><option key={p.id} value={p.id}>{locale==="ar"&&p.nameAr?p.nameAr:p.name}</option>)}</select></label><button className="button primary">{t("save")}</button></form></div><div className="workflow-list">{groups.length?groups.map(group=><article className="dash-card" key={group.id}><header><div><h2>{locale==="ar"&&group.nameAr?group.nameAr:group.name}</h2><small>{group.isRequired?t("required"):`${group.minSelections}–${group.maxSelections}`}</small></div></header><div className="option-chip-list">{group.options.map(({option})=><span key={option.id}>{locale==="ar"&&option.nameAr?option.nameAr:option.name}<b>{Number(option.priceAdjustment)>=0?"+":""}{Number(option.priceAdjustment)}</b></span>)}</div><form action={attach} className="inline-form"><input type="hidden" name="groupId" value={group.id}/><select name="productId">{products.filter(p=>!group.products.some(x=>x.productId===p.id)).map(p=><option key={p.id} value={p.id}>{locale==="ar"&&p.nameAr?p.nameAr:p.name}</option>)}</select><button className="button ghost">{t("attachProducts")}</button></form></article>):<p>{t("empty")}</p>}</div></section>;
}
