import Link from "next/link";
import { prisma } from "@/lib/prisma";

export default async function UsersPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; page?: string }> }) {
  const params = await searchParams; const q = params.q?.trim(); const page = Math.max(1, Number(params.page) || 1); const take = 25;
  const where = { ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" as const } }, { email: { contains: q, mode: "insensitive" as const } }, { phone: { contains: q } }] } : {}), ...(params.status === "active" ? { isActive: true } : params.status === "suspended" ? { isActive: false } : {}) };
  const [users, count] = await Promise.all([prisma.user.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * take, take, select: { id: true, name: true, email: true, phone: true, isActive: true, createdAt: true, roles: { select: { role: true } }, restaurantMemberships: { select: { restaurant: { select: { name: true } } }, take: 2 } } }), prisma.user.count({ where })]);
  return <><header className="admin-header"><div><h1>إدارة المستخدمين</h1><p>البحث، تعديل الحساب، الصلاحيات، الإيقاف، ومساعدة المستخدم في استعادة الوصول.</p></div></header><section className="admin-card"><form className="admin-form"><label>بحث<input name="q" defaultValue={q} placeholder="الاسم أو البريد أو الهاتف"/></label><label>الحالة<select name="status" defaultValue={params.status ?? "all"}><option value="all">الجميع</option><option value="active">نشط</option><option value="suspended">موقوف</option></select></label><button>تصفية</button></form><table className="admin-table"><thead><tr><th>المستخدم</th><th>الهاتف</th><th>الأدوار</th><th>المطاعم</th><th>الحالة</th><th/></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td data-label="المستخدم"><b>{user.name}</b><br/><small>{user.email}</small></td><td data-label="الهاتف">{user.phone ?? "—"}</td><td data-label="الأدوار">{user.roles.map((item) => item.role).join("، ") || "—"}</td><td data-label="المطاعم">{user.restaurantMemberships.map((item) => item.restaurant.name).join("، ") || "—"}</td><td data-label="الحالة"><span className={`admin-pill ${user.isActive ? "" : "off"}`}>{user.isActive ? "نشط" : "موقوف"}</span></td><td data-label="الإجراء"><Link className="admin-button" href={`/super-admin/users/${user.id}`}>فتح الحساب</Link></td></tr>)}</tbody></table><p>{count} مستخدم — صفحة {page}</p></section></>;
}
