import { startOfDay, subDays } from "date-fns";
import { BarChart3, Eye, ShoppingBag, TrendingUp } from "lucide-react";
import { getLocale, getTranslations } from "next-intl/server";
import { prisma } from "@/lib/prisma";
import { requireTenant } from "@/lib/tenant";
export const dynamic = "force-dynamic";
export default async function AnalyticsPage() {
  const { restaurantId } = await requireTenant(); const since = startOfDay(subDays(new Date(), 29));
  const [t, d, locale, restaurant, orders, events, top] = await Promise.all([getTranslations("analytics"), getTranslations("dashboard"), getLocale(), prisma.restaurant.findUniqueOrThrow({ where: { id: restaurantId }, select: { currency: true } }), prisma.order.findMany({ where: { restaurantId, createdAt: { gte: since } }, select: { total: true, status: true, createdAt: true } }), prisma.analyticsEvent.groupBy({ by: ["type"], where: { restaurantId, createdAt: { gte: since } }, _count: { _all: true } }), prisma.orderItem.groupBy({ by: ["productName"], where: { order: { restaurantId, createdAt: { gte: since }, status: { not: "CANCELLED" } } }, _sum: { quantity: true }, orderBy: { _sum: { quantity: "desc" } }, take: 10 })]);
  const completed = orders.filter(order => order.status === "COMPLETED"); const revenue = completed.reduce((sum, order) => sum + Number(order.total), 0); const views = events.find(event => event.type === "MENU_VIEW")?._count._all ?? 0; const scans = events.find(event => event.type === "QR_SCAN")?._count._all ?? 0; const money = (value: number) => new Intl.NumberFormat(locale, { style: "currency", currency: restaurant.currency }).format(value); const daily = Array.from({ length: 30 }, (_, index) => { const date = startOfDay(subDays(new Date(), 29 - index)); return { date, count: orders.filter(order => startOfDay(order.createdAt).getTime() === date.getTime()).length }; }); const max = Math.max(1, ...daily.map(day => day.count));
  return <section className="dash-main"><header><div><small>{t("last30")}</small><h1>{t("title")}</h1><p>{t("subtitle")}</p></div></header><div className="stats"><article><Eye /><p>{d("menuViews")}</p><strong>{views}</strong></article><article><ShoppingBag /><p>{d("todayOrders")}</p><strong>{orders.length}</strong></article><article><TrendingUp /><p>{t("revenue")}</p><strong>{money(revenue)}</strong></article><article><BarChart3 /><p>{t("averageOrder")}</p><strong>{money(completed.length ? revenue / completed.length : 0)}</strong></article></div><article className="dash-card"><h2>{t("dailyOrders")}</h2><div className="analytics-bars">{daily.map(day => <i key={day.date.toISOString()} style={{ height: `${Math.max(3, day.count / max * 100)}%` }} title={`${day.count}`} />)}</div></article><article className="dash-card"><h2>{t("popular")}</h2><div className="rank-list">{top.map((product, index) => <div key={product.productName}><b>{index + 1}</b><span>{product.productName}</span><strong>{product._sum?.quantity ?? 0}</strong></div>)}</div><small>{d("qrScans")}: {scans}</small></article></section>;
}
