import { startOfDay, subDays } from "date-fns";
import { BarChart3, Bike, Eye, ShoppingBag, Store, TrendingUp } from "lucide-react";
import { getLocale, getTranslations } from "next-intl/server";
import { prisma } from "@/lib/prisma";
import { requireTenant } from "@/lib/tenant";
export const dynamic = "force-dynamic";
export default async function AnalyticsPage() {
  const { restaurantId } = await requireTenant(); const since=startOfDay(subDays(new Date(),29));
  const [t,d,empty,deliveryText,locale,restaurant,orders,events,top,drivers]=await Promise.all([
    getTranslations("analytics"),getTranslations("dashboard"),getTranslations("mvpPolish.empty"),getTranslations("restaurantWorkflow.delivery"),getLocale(),
    prisma.restaurant.findUniqueOrThrow({where:{id:restaurantId},select:{currency:true}}),
    prisma.order.findMany({where:{restaurantId,createdAt:{gte:since}},select:{total:true,status:true,createdAt:true,fulfillmentType:true,outForDeliveryAt:true,deliveredAt:true,driver:{select:{id:true,name:true}}}}),
    prisma.analyticsEvent.groupBy({by:["type"],where:{restaurantId,createdAt:{gte:since}},_count:{_all:true}}),
    prisma.orderItem.groupBy({by:["productName"],where:{order:{restaurantId,createdAt:{gte:since},status:{not:"CANCELLED"}}},_sum:{quantity:true},orderBy:{_sum:{quantity:"desc"}},take:10}),
    prisma.order.groupBy({by:["driverId"],where:{restaurantId,driverId:{not:null},createdAt:{gte:since},status:{in:["DELIVERED","COMPLETED"]}},_count:{_all:true},orderBy:{_count:{driverId:"desc"}},take:5}),
  ]);
  const completed=orders.filter(o=>o.status==="COMPLETED");const revenue=completed.reduce((s,o)=>s+Number(o.total),0);const views=events.find(e=>e.type==="MENU_VIEW")?._count._all??0;const scans=events.find(e=>e.type==="QR_SCAN")?._count._all??0;const money=(v:number)=>new Intl.NumberFormat(locale,{style:"currency",currency:restaurant.currency}).format(v);const daily=Array.from({length:30},(_,i)=>{const date=startOfDay(subDays(new Date(),29-i));return{date,count:orders.filter(o=>startOfDay(o.createdAt).getTime()===date.getTime()).length}});const max=Math.max(1,...daily.map(x=>x.count));const delivered=orders.filter(o=>o.outForDeliveryAt&&o.deliveredAt);const averageDelivery=delivered.length?Math.round(delivered.reduce((s,o)=>s+(o.deliveredAt!.getTime()-o.outForDeliveryAt!.getTime())/60000,0)/delivered.length):0;const driverNames=new Map(orders.flatMap(o=>o.driver?[[o.driver.id,o.driver.name]]:[]));
  if(!orders.length&&!events.length)return <section className="dash-main"><header><div><h1>{t("title")}</h1></div></header><article className="dash-card friendly-empty"><BarChart3/><h2>{empty("analyticsTitle")}</h2><p>{empty("analyticsHelp")}</p></article></section>;
  return <section className="dash-main"><header><div><small>{t("last30")}</small><h1>{t("title")}</h1><p>{t("subtitle")}</p></div></header><div className="stats"><article><Eye/><p>{d("menuViews")}</p><strong>{views}</strong></article><article><ShoppingBag/><p>{d("todayOrders")}</p><strong>{orders.length}</strong></article><article><TrendingUp/><p>{t("revenue")}</p><strong>{money(revenue)}</strong></article><article><BarChart3/><p>{t("averageOrder")}</p><strong>{money(completed.length?revenue/completed.length:0)}</strong></article><article><Bike/><p>{deliveryText("delivery")}</p><strong>{orders.filter(o=>o.fulfillmentType==="DELIVERY").length}</strong></article><article><Store/><p>{deliveryText("pickup")}</p><strong>{orders.filter(o=>o.fulfillmentType==="PICKUP").length}</strong></article><article><Store/><p>{deliveryText("dineIn")}</p><strong>{orders.filter(o=>o.fulfillmentType==="DINE_IN").length}</strong></article><article><Bike/><p>{deliveryText("eta")}</p><strong>{averageDelivery} min</strong></article></div><article className="dash-card"><h2>{t("dailyOrders")}</h2><div className="analytics-bars">{daily.map(day=><i key={day.date.toISOString()} style={{height:`${Math.max(3,day.count/max*100)}%`}} title={`${day.count}`}/>)}</div></article><div className="dash-grid"><article className="dash-card"><h2>{t("popular")}</h2><div className="rank-list">{top.map((p,i)=><div key={p.productName}><b>{i+1}</b><span>{p.productName}</span><strong>{p._sum.quantity??0}</strong></div>)}</div><small>{d("qrScans")}: {scans}</small></article><article className="dash-card"><h2>{deliveryText("title")}</h2><div className="rank-list">{drivers.map((driver,i)=><div key={driver.driverId}><b>{i+1}</b><span>{driver.driverId?driverNames.get(driver.driverId)??driver.driverId:"—"}</span><strong>{driver._count._all}</strong></div>)}</div></article></div></section>;
}
